source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1"
gem "puma", "~> 6.0"
gem "pg", "~> 1.5"

group :development, :test do
  gem "rspec", "~> 3.12"
  gem "rubocop", require: false
end

group :development do
  gem "web-console"
end
